language: java

jdk:
  - openjdk13

cache:
  directories:
    - $HOME/.m2

install:
  - mvn clean install -Dmaven.javadoc.skip=true -DskipTests=true -B -V

deploy:
  - provider: script
    script: mvn deploy -Dregistry=https://maven.pkg.github.com/digital-delivery-academy -Dtoken=$GITHUB_PACKAGE_DEPLOY_TOKEN
    on:
      tags: true
  - provider: script
    script: mvn package com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_API_TOKEN

notifications:
  slack: evoco:HMLAFFFsZHDFu6xBw0OyXZrp