dist: trusty

language: java

jdk:
  - openjdk12

cache:
  directories:
    - $HOME/.m2

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - "cp .travis.settings.xml $HOME/.m2/settings.xml"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - google-chrome-stable --remote-debugging-port=9222 http://localhost &
  - chmod ugo+x scripts/publish-javadocs-to-github-pages.sh

addons:
  firefox: latest

install:
  - mvn clean install -Dmaven.javadoc.skip=true -B -V

deploy:
  - provider: script
    script: mvn deploy -DskipTests -Dregistry=https://maven.pkg.github.com/digital-delivery-academy -Dtoken=$GITHUB_PACKAGE_DEPLOY_TOKEN
    on:
      tags: true
  - provider: script
    script: mvn package com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_API_TOKEN
    on:
      all_branches: true
  - provider: script
    script:
      -  mvn javadoc:javadoc
      - ./scripts/publish-javadocs-to-github-pages.sh
    on:
      branch: publish-javadocs-issue-#6

notifications:
  slack: evoco:HMLAFFFsZHDFu6xBw0OyXZrp