dist: trusty
language: java
jdk:
- openjdk13
cache:
  directories:
  - "$HOME/.m2"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_install:
- openssl aes-256-cbc -K $encrypted_25a884814f46_key -iv $encrypted_25a884814f46_iv
  -in deployment/signingkey.asc.enc -out deployment/signingkey.asc -d
- cp .travis.settings.xml $HOME/.m2/settings.xml
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
- google-chrome-stable --remote-debugging-port=9222 http://localhost &
- chmod ugo+x scripts/publish-javadocs-to-github-pages.sh
- chmod ugo+x scripts/get-bank-holiday-data-source-and-store-in-resources.sh
addons:
  firefox: latest
install:
- mvn clean install -Dmaven.javadoc.skip=true -B -V
- bash scripts/get-bank-holiday-data-source-and-store-in-resources.sh
after_success:
- gpg2 --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --no-default-keyring --import deployment/signingkey.asc
- gpg2 --allow-secret-key-import --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring
  --import deployment/signingkey.asc
- mvn clean deploy -Dgpg.executable=gpg2 -Dgpg.keyname=5F84CD1775351968CABF0B0D779D2423E1D24D89
  -Dgpg.passphrase=$GPG_PASSPHRASE -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/pubring.gpg -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/secring.gpg
deploy:
- provider: script
  script: mvn test com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml
    -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_API_TOKEN
  on:
    branch: master
- provider: script
  script: bash scripts/publish-javadocs-to-github-pages.sh
  on:
    tags: true