dist: trusty
language: java
jdk:
- openjdk13
cache:
  directories:
  - "$HOME/.m2"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_install:
- cp .travis.settings.xml $HOME/.m2/settings.xml
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
- google-chrome-stable --remote-debugging-port=9222 http://localhost &
- chmod ugo+x scripts/publish-javadocs-to-github-pages.sh
- chmod ugo+x scripts/get-bank-holiday-data-source-and-store-in-resources.sh
addons:
  firefox: latest
install:
- mvn clean install -Dmaven.javadoc.skip=true -B -V
- bash scripts/get-bank-holiday-data-source-and-store-in-resources.sh
- mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
deploy:
- provider: script
  script: bash scripts/publish-javadocs-to-github-pages.sh
  on:
    tags: true