language: java

jdk:
  - openjdk13

cache:
  directories:
    - $HOME/.m2

install:
  - mvn clean install -Dmaven.javadoc.skip=true -DskipTests=true -B -V

deploy:
  - provider: script
    script: mvn deploy -Dregistry=https://maven.pkg.github.com/digital-delivery-academy/selenium-pom-example -Dtoken=$GITHUB_PACKAGE_DEPLOY_TOKEN
    on:
      tags: true

notifications:
  slack: evoco:HMLAFFFsZHDFu6xBw0OyXZrp