# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Setup display for running Chrome
      run: |
        chmod ugo+x scripts/publish-javadocs-to-github-pages.sh
        chmod ugo+x scripts/get-bank-holiday-data-source-and-store-in-resources.sh
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run SonarQube
      run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
    - name: Get bank holidays
      run: bash scripts/get-bank-holiday-data-source-and-store-in-resources.sh
